### ISSUE TITLE
Create draft design for message matching

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#44]
We need the ability to match on messages, but there are open questions about what this API should look like. We'll need to work through the different capabilities in `pact_matching` that we ought to expose, how those can/should be used on the C side, and whether it can be split into parts for separate implementation.

**Comment by alilleybrinker** [comment]
Alright, after some deep-dive work for `pact_matching`'s matcher implementation, I believe I have sketched out a minimal initial effort for message matching.

The key function is in `pact_matching/src/lib.rs`, and is [`match_message`](https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching/src/lib.rs#L1360-L1374). This takes in two `Message` values, and produces a `Vec<Mismatch>`. So, the most basic solution is to expose this function over FFI, and wrap `Vec<Mismatch>` in an FFI-friendly way with an opaque pointer, as we've done. It's already on the heap, and we could use something like `Vec::into_boxed_slice` combined with `Box::leak` to leak it safely, and then provide a destructor which rebuilds using `Vec`'s `From<Box<[T]>>` implementation.

So, this would give the FFI-user a set of mismatches, but nothing to do with them. `Mismatch` has [a collection of methods](https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching/src/lib.rs#L585-L722) for getting information about them, which we'd need to expose as well.

This, along with our existing ability to create `Message`s from JSON, would allow matching on messages.

One additional note is how to handle iteration over the `Vec<Mismatch>` FFI-friendly type (`Mismatches`?). We'd probably want `mismatches_get_iter`, `mismatches_iter_next`, and `mismatches_iter_delete`.

What this _doesn't_ cover includes:

* Reading the matchers loaded from JSON for `Message`s.
* Matching anything else.

The list of things to expose would be:

* `match_message`
* `Mismatches`
* `mismatches_get_iter`
* `mismatches_delete`
* `MismatchesIterator`
* `mismatches_iter_next`
* `mismatches_iter_delete`
* `Mismatch`
* `mismatch_to_json`
* `mismatch_type`
* `mismatch_summary`
* `mismatch_description`
* `mismatch_ansi_description`

So that's 3 new types to expose (`Mismatches`, `MismatchesIterator`, and `Mismatch`), plus 10 new functions. No `mismatch_delete` function is necessary because they're owned in the `Mismatches` vector and will be freed by `mismatches_delete`.

**Comment by alilleybrinker** [comment]
Any input before I implement this, @ewalters-mitre? Looking to get this done before COB Wednesday.

**Comment by ewalters-mitre** [comment]
So, I was under the impression that we were going to have a follow-up meeting on this to compare vs. what had already been implemented on the C++ side, but I don't want to hold you up, and time is tight for me today.  

Let's do this: I'll make sure I have that comparison ready for tomorrow's meeting, but in the meantime you can go full-speed ahead, since I suspect we'll have leverage most of what you are doing regardless.  Sound good?

**Comment by alilleybrinker** [comment]
My apologies, you're right. We can still have a meeting if you'd like. Otherwise, I'm happy with the plan you suggest.
