### ISSUE TITLE
FFI for reading pact_matching::models::Message fields

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#5]
Be able to at least get pointers to the more complex field types.

- [x] `description`
- [x] `provider_states`
    - [ ] Implement FFI for `ProviderState` type (at least to be visible to C code as an opaque pointer)
- [ ] `contents`
    - [ ] Implement FFI for `OptionalBody` type (at least to be visible to C code as an opaque pointer)
- [x] `metadata`
    - [x] Implement FFI for `HashMap<String, String>` type (note that C can't be generic like Rust can, so we should consider how to approach `HashMap` FFI)
- [ ] `matching_rules`
    - [ ] Implement FFI for `MatchingRules` (at least to be visible to C code as an opaque pointer)

**Comment by asteffey** [comment]
Just a clarification - for mitre/pact-cplusplus#3 and mitre/pact-cplusplus#5, the priority is the `description` and `provider_states` fields.  More complex fields, like `matching_rules` can be deferred.

**Comment by alilleybrinker** [comment]
With https://github.com/mitre/pact-reference/pull/29 done, I've checked off provider states from the list up top. I've also asked @djorgensen-mitre what our next priority ought to be. @asteffey if you have thoughts too, let me know.
