### ISSUE TITLE
Message matching in FFI should compare Message handle vs. string instead of two handles.

### ISSUE THREAD

**Issue by ewalters-mitre** [mitre/pact-reference#59]
`const Mismatches *match_message(const Message *msg_1, const Message *msg_2); ` should instead have a signature of:
`const Mismatches *match_message(const Message *msg_1, const char *actual_msg); ` since we're technically not matching a Message *, which is a Pact message handle against another handle.  Instead we should be matching the Pact Message (with matching rules and expected message context) against an actual message as string content.

**Comment by alilleybrinker** [comment]
I recall not being sure how to pursue the right API design here. I'll need to investigate before I can estimate how tough this will be.

**Comment by ewalters-mitre** [comment]
I understand that this part was fuzzy.  Happy to act as a sounding board if you need one.

If it looks like both params should be messages, then that's ok but it must be properly motivated.

**Comment by alilleybrinker** [comment]
After some spelunking in `pact_matching` and `pact_verifier`, I think we have an approach:

We'll add a new FFI constructor for `Message` called `message_from_body` that looks like `message_from_body(const char *body, const char* content_type) -> *mut Message`. The `content_type` field is necessary to initialize `OptionalBody` inside the `Message`, although in our case the type is always an XML content-type (`application/xml`). The `Message` returned from this new constructor can be used with `match_message`.
